"""Modificado campo de  newsletters por tipo Email

Revision ID: 83efe3328ac3
Revises: dfa374508052
Create Date: 2023-10-29 18:21:42.641946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '83efe3328ac3'
down_revision: Union[str, None] = 'dfa374508052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletters', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlalchemy_utils.types.email.EmailType(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletters', 'email',
               existing_type=sqlalchemy_utils.types.email.EmailType(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
