"""Modificando el uso de caracteres unicode

Revision ID: bd2544cdb5fe
Revises: faf9ef363daf
Create Date: 2023-10-16 19:41:27.679329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2544cdb5fe'
down_revision: Union[str, None] = 'faf9ef363daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
