"""Reestructura de la tabla de productos y agregada la tabla marca

Revision ID: de4f3d821444
Revises: fcec552bf9b0
Create Date: 2023-10-16 17:30:13.322008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4f3d821444'
down_revision: Union[str, None] = 'fcec552bf9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacies_name'), 'pharmacies', ['name'], unique=True)
    op.add_column('branches', sa.Column('pharmacy_id', sa.Integer(), nullable=False))
    op.drop_constraint('branches_brand_id_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'pharmacies', ['pharmacy_id'], ['id'])
    op.drop_column('branches', 'brand_id')
    op.alter_column('brands', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('products', sa.Column('pharmacy_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'products', 'pharmacies', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'pharmacy_id')
    op.alter_column('brands', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('branches', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key('branches_brand_id_fkey', 'branches', 'brands', ['brand_id'], ['id'])
    op.drop_column('branches', 'pharmacy_id')
    op.drop_index(op.f('ix_pharmacies_name'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
