"""Agregada tabla newsletters

Revision ID: dfa374508052
Revises: f41a29937d3c
Create Date: 2023-10-29 18:12:34.666874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa374508052'
down_revision: Union[str, None] = 'f41a29937d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletters_email'), 'newsletters', ['email'], unique=True)
    op.create_index(op.f('ix_newsletters_id'), 'newsletters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletters_id'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_email'), table_name='newsletters')
    op.drop_table('newsletters')
    # ### end Alembic commands ###
