"""Creada tabla para la sugerencia de productos

Revision ID: eba25a53cf89
Revises: 83efe3328ac3
Create Date: 2023-10-29 22:25:19.132378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba25a53cf89'
down_revision: Union[str, None] = '83efe3328ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('details', sa.UnicodeText(), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('medicine_name', sa.String(length=50), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_id'), 'suggestions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_id'), table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
