"""Corregido error de relacion en la tabla Brand

Revision ID: faf9ef363daf
Revises: de4f3d821444
Create Date: 2023-10-16 18:27:48.723168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf9ef363daf'
down_revision: Union[str, None] = 'de4f3d821444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
